### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by manzt** [manzt/juv#13]
Should be straightforward to add, just need to fight with CI a bit to understand what the issues are.

**Comment by manzt** [comment]
Need to use subprocess in for win32 systems because execvp does not exist.

**Comment by ATL2001** [comment]
super cool project, I've got the run command working on windows over here on my end, want me to open a PR?

**Comment by manzt** [comment]
Glad to hear it! Yes, that would be amazing--thank you for offering to work on a contribution. The reason we don't officially support windows is mostly because I don't have a machine to try out myself, and CI tests were failing on windows. Feel free to open a PR and we can go from there

**Comment by ATL2001** [comment]
I seem to have celebrated too early, I've got it opening the notebook in jupyterlab without issue, but when I shutdown jupyterlab it doesn't exit cleanly. it's complaining about not being able to delete ~juv\\juv\\tmp8f06lo3r\\nbsignatures.db, which I think must be related to the temp dir [created in the setup of the jupyter data dir](https://github.com/manzt/juv/blob/5bdf24ff160b43330dc26174745a8ec895a53b32/src/juv/_run_template.py#L66). I'll fool around with it some more and see if I can get part that working too, but probably not today, I've got turkey to eat 😄🦃.

**Comment by manzt** [comment]
no problem! happy turkey day—thanks again for your willingness to take some of this on when you can

**Comment by manzt** [comment]
Closing for now, thanks to #54!
