### ISSUE TITLE
Adding dependencies without the version numbers causes parsing error

### ISSUE THREAD

**Issue by alonsosilvaallende** [manzt/juv#4]
Adding dependencies without the version numbers causes parsing error
To reproduce:
``
uvx juv init
``
``
uvx juv add Untitled.ipynb numpy pandas
``
``
uvx juv lab Untitled.ipynb
``
> error: Failed to parse: `numpy,pandas`
>  Caused by: Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `,`
> numpy,pandas
>           ^

**Comment by manzt** [comment]
Adding packages without versions should work just fine. It appears your ran:

```sh
uvx juv add numpy,pandas
```

(notice the comma). Packages should be separated by a space. It's consistent with `uv add --script foo.py numpy pandas`.

**Comment by alonsosilvaallende** [comment]
I don't think so. I redid it again with space (not comma) and it gives the same error.
![Screenshot 2024-10-21 142745](https://github.com/user-attachments/assets/eda5d335-8432-4d08-a54b-a47bd1a691ba)

**Comment by alonsosilvaallende** [comment]
Same error.
![Screenshot 2024-10-21 144039](https://github.com/user-attachments/assets/e0a72c41-800a-4ef5-97d6-92c41409a800)

**Comment by manzt** [comment]
hmm

**Comment by alonsosilvaallende** [comment]
I updated uv and now it works. No idea what was the problem. Sorry.

**Comment by alonsosilvaallende** [comment]
I updated uv and now it works. No idea what was the problem. Sorry.

**Comment by manzt** [comment]
All good! This issue convinced me we should have a `info` subcommand (added in v0.1.5), which will print the juv and uv versions and hopefully will be easier for debugging in the future. 

```sh
❯ uvx juv@latest info
juv 0.1.5
uv 0.4.24 (b9cd54913 2024-10-17)
```
