### ISSUE TITLE
add deps to `script.py`

### ISSUE THREAD

**Issue by tlambert03** [manzt/juv#48]
the readme describes using `uvx run script.py`, with implicit conversion to ipynb... but you don't seem to be able to add dependencies using, e.g. `uvx juv add script.py pandas`

is that in scope?

**Comment by manzt** [comment]
don’t need us! `uv add —script script.py pandas` :)

and if you don’t want to run with jupyter,

`uv run script.py`

**Comment by tlambert03** [comment]
woah.  uv has grown so fast, so much i need to catch up with beyond just making environments and installing
