### ISSUE TITLE
"remove" command for juv notebooks

### ISSUE THREAD

**Issue by ATL2001** [manzt/juv#58]
uv has the [remove](https://docs.astral.sh/uv/reference/cli/#uv-remove) command to remove a dependency, it would be nice to have this available in juv as well (for those of us who type names of packages wrong 😄 and then the juv run command complains it can't find the pacakge)

I just opened the notebook as text and deleted my errant line and all was well 

(working great over here on windows BTW 👍)

**Comment by manzt** [comment]
Great suggestion! Implemented in #59, and released in v0.2.28.

**Comment by ATL2001** [comment]
I hadn't looked at the code yet to be sure, but I was pretty sure that was going to be an easy request 😄👍

**Comment by ATL2001** [comment]
thank you!
