### ISSUE TITLE
How to change the listening host?

### ISSUE THREAD

**Issue by amyb-asu** [manzt/juv#60]
I am running this on a headless device, so I need to change the listening host so that it is 0.0.0.0, but I cannot see a way to do this? Is it supported?

**Comment by manzt** [comment]
Hi there, you can pass additional flags to the underlying jupyter runtime in `juv run` following `--`. E.g.,

```sh
juv run notebook.ipynb -- --ip=0.0.0.0 --no-browser --port=8889
```
